# Makefile for building an Xcode project

# Define the scheme and configuration
SCHEME = "SimpleX (iOS)"
CONFIGURATION = Debug

# Define the default make target
all: build

# Target to build the project
build:
	xcodebuild -scheme $(SCHEME) -configuration $(CONFIGURATION) build

# Target to clean the build
clean:
	xcodebuild -scheme $(SCHEME) -configuration $(CONFIGURATION) clean

# Additional targets can be added as needed
